---
- assert:
    that:
      - wildfly is defined
      - wildfly.home is defined
      - wildfly.user is defined
      - wildfly.group is defined
      - wildfly.config is defined
      - wildfly.config.base is defined
    quiet: true

- set_fact:
    basedir: "{{ wildfly.basedir_prefix | default(wildfly.home + '/standalone') }}"
  when:
    - not instance_id is defined

- block:
    - assert:
        that:
          - wildfly.basedir_prefix is defined
        quiet: true
        fail_msg: "If instance_id is set, wildfly.basedir_prefix must also be defined."

    - set_fact:
        basedir: "{{ wildfly.basedir_prefix }}{{ instance_id }}"

    - assert:
        that:
          - wildfly.config.name is defined
        fail_msg: "If instance_id is set, wildfly.config.name must be defined too."
        quiet: true

    - set_fact:
        instance_name: "{{ wildfly.config.name }}-{{ instance_id }}"
  when:
    - instance_id is defined

- set_fact:
    instance_name: "{{ wildfly.instance_name | default('wildfly') }}"
  when:
    - instance_name is not defined

- name : "Creates basedir {{ basedir }} for instance: {{ instance_name }}"
  file:
    path: "{{ basedir }}"
    state: directory
    owner: "{{ wildfly.user }}"
    group: "{{ wildfly.group }}"
    mode: '0755'

- name : "Creates deployment directories for instance: {{ instance_name }}"
  file:
    path: "{{ basedir }}/deployments"
    state: directory
    owner: "{{ wildfly.user }}"
    group: "{{ wildfly.group }}"
    mode: '0755'

- name: "Deploy Wildfy configuration"
  copy:
    src: "{{ wildfly.home }}/standalone/configuration/{{ wildfly.config.base }}"
    dest: "{{ wildfly.home }}/standalone/configuration/{{ instance_name }}.xml"
    group: "{{ wildfly.group }}"
    owner: "{{ wildfly.user }}"
    remote_src: true
    force: no

- name: "Deploy Systemd configuration for Wildfly service"
  template:
    src: templates/systemd/wfly.service.j2
    dest: "/usr/lib/systemd/system/{{ instance_name }}.service"
    group: root
    owner: root
  register: daemon_reload

- name: "Deploy Wildfly service instance configuration"
  template:
    src: templates/systemd/wfly.conf.j2
    dest: "/etc/{{ instance_name }}.conf"
    group: root
    owner: root

- name: "Perform daemon-reload to ensure the changes are picked up"
  systemd:
    daemon_reload: yes
  when:
    - daemon_reload is defined
    - daemon_reload.changed

- name: "Start Wildfly Server named {{ instance_name }}"
  service:
    name: "{{ instance_name }}"
    state: started
    enabled: yes
